<?php

namespace Caishni\Fawry\Models;

use Caishni\Fawry\Facades\FawryPay;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Database\Eloquent\Model;

class UserCard extends Model
{
    protected $fillable = ['token', 'last_four_digits'];

    public function user()
    {
        return $this->belongsTo(config("auth.providers.users.model"));
    }

    public function charge($cvv, Collection $items, string $referenceNumber, string $description)
    {
        return FawryPay::chargeCardToken($this, $cvv, $items, $referenceNumber, $description);
    }

    public function delete()
    {
        FawryPay::deleteCardToken($this);
        return parent::delete(); // TODO: Change the autogenerated stub
    }
}
